version: "3"
services:
  app:
    build: .
    expose:
      - "3000"
    container_name: app
    restart: unless-stopped
    networks:
      - app-network
  nginx:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - app
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "4000:4000"
networks:
  app-network:
    driver: bridge